blank_issues_enabled: false
contact_links:
  - name: 💬 Community Discussions
    url: https://github.com/yourusername/microcrowd/discussions
    about: Ask questions and discuss ideas with the community
  - name: 📚 Documentation
    url: https://github.com/yourusername/microcrowd#readme
    about: Check the README for setup instructions and usage guidelines